fix issue #23 - zeroing the output vector in the mTracker loop
flucoma/flucoma-core pull request #82
Opened 2022-01-20 11:15 UTC by tremblap

This test code should show the difference.

```
x = {|nband=10| FluidChroma.kr(WhiteNoise.ar(0.2), nband, normalize: 1, maxNumChroma: 12).poll(1)}.play
//10 wiggles

x.set(\nband, 4)
//sample and hold instead of 0 for bands 5-10 (now fixed)

// ====

x = {|nband=10| FluidMelBands.kr(WhiteNoise.ar(0.2),nband,maxNumBands: 10).poll(1)}.play
//10 wiggles

x.set(\nband, 4)
//sample and hold instead of 0 for bands 5-10

// ====

x = {|nband=10| FluidMFCC.kr(WhiteNoise.ar(0.2),nband,maxNumCoeffs: 13).poll(1)}.play
//10 wiggles

x.set(\nband, 4)
//sample and hold instead of 0 for bands 5-10

s.reboot
```

2022-01-20 11:26 UTC, weefuzzy requested changes
This isn't quite what I suggested. Filling `output[0]` only when the parameter value changes makes the assumption that whatever `output[0]` points to is the same thing between invocations of `process()`. I don't think that's a guarantee we make. 

Instead, my suggestion was that you fill the remainder of the output vector when the function returns by writing something like `output[0](Slice(get<kNBands>()).fill(0)` after the chroma values have been assigned.

2022-01-20 11:32 UTC, weefuzzy commented
The problem is here: 

https://github.com/flucoma/flucoma-docs/blob/0e970cb811e59e541ec41348e69c9302af254a45/flucoma/doc/raw/driver.py#L15-L18

maybe try resolving the path or somethng?

2022-01-20 11:50 UTC, tremblap commented
I am not yet good enough to understand why process() would not get the same output[0] but I have an intuition... but adding 0s every time seems heavy-handed, no? I'll give it a spin.

2022-01-20 12:01 UTC, tremblap commented
your solution works, except when kNXXX == kMaxXXX, which spits all 0s

before I do a if, or put the zeroing in front, is there anything I could do better in the world of FluidTensor(View)

2022-01-20 12:03 UTC, weefuzzy commented
`output[0]` is, at heart, a pointer and the Client knows nothing about the provenance of that pointer. It could be something provided by the host *wrapper* or the host itself. In any case, assuming that it remains pointing to the same thing between invocations involves also making assumptions about how hosts and wrappers behave, and how the lifetime of the client might relate to, e.g., the lifetime of a particular job in the host. It will happen to work in real-time usage in Max, PD, SC at the moment. Pretty sure it will break in the `Buf` versions. 

Writing a few zeros isn't at all heavy handed relative to the amount of other work that's going on.

2022-01-20 12:08 UTC, tremblap commented
thanks again for the thorough explanation as usual. I'm still puzzled why the Slice of length 0 is zeroing all but i can work around

2022-01-20 12:09 UTC, weefuzzy commented
> your solution works, except when kNXXX == kMaxXXX, which spits all 0s
> 
> before I do a if, or put the zeroing in front, is there anything I could do better in the world of FluidTensor(View)

Hmmph. Maybe pass the slice size explicitly 

output[0](Slice(get<kNBands>(),get<kMaxBands>() - get<kNBands>())).fill(0)

2022-01-20 12:20 UTC, tremblap commented
This works:
    output[0](Slice(get<kNChroma>(), get<kMaxNChroma>() - get<kNChroma>())).fill(0);

and this works too and I find it clearer conceptually:
    if (get<kNChroma>() != get<kMaxNChroma>()) output[0](Slice(get<kNChroma>())).fill(0);

maybe it should be < instead of !=

2022-01-20 12:28 UTC, weefuzzy commented
I'd rather not add extra branches into a code hot path where we don't need them: the point is that this condition is checked anyway, so no need to do it twice.

2022-01-20 12:34 UTC, tremblap commented
You are hard on me. So it is better to send a 0size Slice (when the subtraction is 0)  than a fork? I'll follow your lead and learn strange conventions :)

2022-01-20 12:43 UTC, weefuzzy commented
Yes, otherwise the branch predictor's job is just more complex for no benefit. The thing iterating the slice is going to be doing something like `while(current != end){...}` anyway, so a replicating this branch is redundant.

2022-01-20 13:05 UTC, tremblap commented
I was just trying to remove a subtraction :)

2022-01-20 13:07 UTC, weefuzzy commented
Branching is worse ;-)

2022-01-20 13:28 UTC, tremblap commented
Properly working now

2022-01-21 14:47 UTC, weefuzzy approved these changes

2022-01-24 14:17 UTC, merged